Lab2_Cifrado/Models/Serie1/Cesar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.ComponentModel.DataAnnotations;
using BibliotecaDeClases.Cifrado.Cesar;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Models.Serie1
{
    public class Cesar
    {
        [Display(Name = "Clave")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Debe de ingresar una clave para esta operacion")]
        public string PalabraClave { get; set; }

        public string NombreArchivo { get; set; }
        private string RutaAbsolutaArchivo { get; set; }
        private string RutaAbsolutaServer { get; set; }
        private string Extension { get; set; }

        private CifradoCesar CesarCif { get; set; }
        private DescifradoCesar CesarDescif { get; set; }

        public Cesar()
        {
            PalabraClave = string.Empty;
            NombreArchivo = string.Empty;
            RutaAbsolutaArchivo = string.Empty;;
            RutaAbsolutaServer = string.Empty;
        }

        public void AsignarExtension(string ext)
        {
            Extension = ext;
        }

        public void AsignarRutas(string rutaAbsServer, string rutaAbsArchivo, string nombreArchivo)
        {
            NombreArchivo = nombreArchivo;
            RutaAbsolutaArchivo = rutaAbsArchivo;
            RutaAbsolutaServer = rutaAbsServer;
        }

        public void Operar()
        {
            var valida = false;

            switch (Extension)
            {
                case "txt":

                    CesarCif = new CifradoCesar(PalabraClave, NombreArchivo, RutaAbsolutaArchivo, RutaAbsolutaServer);

                    valida = CesarCif.ValidarClave(PalabraClave.ToCharArray());
                    if (valida)
                    {                        
                        CesarCif.Cifrar();
                    }                    
                    break;

                case "cif":

                    CesarDescif = new DescifradoCesar(PalabraClave, NombreArchivo, RutaAbsolutaArchivo, RutaAbsolutaServer);

                    valida = CesarDescif.ValidarClave(PalabraClave.ToCharArray());
                    if (valida)
                    {                        
                        CesarDescif.Descifrar();
                    }
                    break;
            }
        }

        //BUSCA DENTRO DE LA CARPETA DE "MisCifrados" DEL SERVER EL ARCHIVO PARA DÁRSELO AL USUARIO
        public FileStream ArchivoResultante(ref string extension)
        {
            switch (Extension)
            {
                case "txt":
                    var path = RutaAbsolutaServer + NombreArchivo + ".cif";
                    var file = new FileStream(path,FileMode.Open,FileAccess.Read);
                    extension = ".cif";
                    return file;

                case "cif":
                    var path2 = RutaAbsolutaServer + NombreArchivo + ".txt";
                    var file2 = new FileStream(path2, FileMode.Open, FileAccess.Read);
                    extension = ".txt";
                    return file2;
            }
            return null;
        }


        //Reset, para cuando se le da home y que vuelva instanciar
        public void Reset()
        {
            switch (Extension)
            {
                case "cif":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".txt");
                    CesarDescif = new DescifradoCesar("","","","");
                    break;

                case "txt":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".cif");
                    CesarCif = new CifradoCesar("", "", "", "");
                    break;
            }
            Data.Instancia.ArchivoCargado = false;
            Data.Instancia.EleccionOperacion = false;
        }
    }
}

Lab2_Cifrado/Controllers/Serie1/CesarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Controllers.Serie1
{
    public class CesarController : Controller
    {
        // GET: Cesar
        public ActionResult IndexCesar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CargaArchivoCesar(HttpPostedFileBase postedFile)
        {
            var FilePath = string.Empty;

            if (postedFile != null)
            {
                var path = Data.Instancia.RutaAbsolutaServer;

                FilePath = path + Path.GetFileName(postedFile.FileName);
                postedFile.SaveAs(FilePath);

                var nombre = postedFile.FileName.Split('.')[0];

                Data.Instancia.CesarCif.AsignarRutas(path,FilePath,nombre);
                Data.Instancia.CesarCif.AsignarExtension(postedFile.FileName.Split('.')[1]);

                Data.Instancia.ArchivoCargado = true;
            }

            return RedirectToAction("IndexCesar");
        }
        
        // POST: Cesar/Create
        [HttpPost]
        public ActionResult OperarCesar(FormCollection collection)
        {
            try
            {
                var clave = collection["PalabraClave"];

                if (clave != "")
                {
                    Data.Instancia.CesarCif.PalabraClave = clave;
                    Data.Instancia.EleccionOperacion = true;
                    Data.Instancia.CesarCif.Operar();
                }
                
                return RedirectToAction("IndexCesar");
            }
            catch (Exception e)
            {
                return View("IndexCesar");
            }
        }

        //NUEVO PARA DESCARGAR ARCHIVO
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Resultado(FormCollection collection)
        {
            try
            {
                if (collection["DescargarCesar"] != null)
                {
                    return RedirectToAction("DescargarResultadoCesar");
                }

                if (collection["HomeSerie1"] != null)
                {
                    Data.Instancia.CesarCif.Reset();
                    return RedirectToAction("PaginaPrincipalLab", "Home");
                }
            }
            catch(Exception error)
            {
                Data.Instancia.CesarCif.Reset();
                return View("IndexCesar");
            }

            return null;
        }
        
        public FileResult DescargarResultadoCesar()
        {
            var extensionNueva = string.Empty;

            return File(Data.Instancia.CesarCif.ArchivoResultante(ref extensionNueva), "*" + extensionNueva,Data.Instancia.CesarCif.NombreArchivo + extensionNueva);
        }
    }
}

Lab2_Cifrado/Views/Cesar/IndexCesar.cshtml
@using Lab2_Cifrado.Instancia
@model Lab2_Cifrado.Models.Serie1.Cesar

@{
    ViewBag.Title = "Cesar |";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Cifrado César</h2>
@if (Data.Instancia.ArchivoCargado == false)
{
    @Html.Partial("_CargaArchivoCesar")
}

@if (Data.Instancia.ArchivoCargado)
{
    @Html.Partial("_OperarCesar")
}

@if (Data.Instancia.ArchivoCargado && Data.Instancia.EleccionOperacion)
{
    @Html.Partial("_ResultadoCesar")
}

Lab2_Cifrado/Views/Cesar/_CargaArchivoCesar.cshtml
@model Lab2_Cifrado.Models.Serie1.Cesar

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">3. Carga de Archivo</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("CargaArchivoCesar", "Cesar", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" class="form-control-file" name="postedFile" aria-describedby="fileHelp">
            <br />
            <button type="submit" class="btn btn-info">Cargar</button>
        }
    </div>
</div>

Lab2_Cifrado/Views/Cesar/_OperarCesar.cshtml
@model Lab2_Cifrado.Models.Serie1.Cesar

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">4. Ingrese la palabra clave</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("OperarCesar", "Cesar"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.PalabraClave, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.PalabraClave, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PalabraClave, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cifrar/Descifrar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Lab2_Cifrado/Views/Cesar/_OperarEspiral.cshtml
@model Lab2_Cifrado.Models.Serie1.Cesar

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">4. Ingrese la palabra clave</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("OperarCesar", "Cesar"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.PalabraClave, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.PalabraClave, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PalabraClave, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cifrar/Descifrar" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Lab2_Cifrado/Views/Cesar/_ResultadoCesar.cshtml
@using Lab2_Cifrado.Instancia
@model Lab2_Cifrado.Models.Serie1.Cesar

@using (Html.BeginForm("Resultado","Cesar"))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">4. Resultado de la operacion</h3>
        </div>
        <div class="panel-body">
            <input type="submit" value="Descargar" class="btn btn-info" name="DescargarCesar" />
            <input type="submit" value="Home" class="btn btn-default" name="HomeSerie1" />
        </div>
    </div>
}