Lab2_Cifrado/Models/Serie1/ZigZag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;
using BibliotecaDeClases.Cifrado.ZigZag;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Models.Serie1
{
    public class ZigZag
    {
        [Display(Name = "Clave/Niveles")]
        [Range(0,Int32.MaxValue,ErrorMessage = "El valor {0} no es válido")]
        [Required(ErrorMessage = "Debe de ingresar una clave para este cifrado")]
        public int Clave { get; set; }
        
        public string NombreArchivo { get; set; }
        private string RutaAbsolutaArchivo { get; set; }
        private string RutaAbsolutaServer { get; set; }
        private string Extension { get; set; }

        private ZigZagCifrado CifradoZigZag { get; set; }
        private ZigZagDescifrado DescifradoZigZag { get; set; }

        public ZigZag()
        {
            Clave = 0;
            NombreArchivo = string.Empty;
            RutaAbsolutaArchivo = string.Empty;;
            RutaAbsolutaServer = string.Empty;
        }

        public void AsignarExtension(string ext)
        {
            Extension = ext;
        }

        public void AsignarRutas(string rutaAbsServer, string rutaAbsArchivo, string nombreArchivo)
        {
            NombreArchivo = nombreArchivo;
            RutaAbsolutaArchivo = rutaAbsArchivo;
            RutaAbsolutaServer = rutaAbsServer;
        }

        public void Operar()
        {
            switch (Extension)
            {
                case "txt":
                    CifradoZigZag = new ZigZagCifrado(NombreArchivo,RutaAbsolutaArchivo,RutaAbsolutaServer,Clave);
                    CifradoZigZag.Cifrar();
                    break;

                case "cif":
                    DescifradoZigZag = new ZigZagDescifrado(NombreArchivo, RutaAbsolutaArchivo, RutaAbsolutaServer,Clave);
                    DescifradoZigZag.Descifrar();
                    break;
            }
        }

        //BUSCA DENTRO DE LA CARPETA DE "MisCifrados" DEL SERVER EL ARCHIVO PARA DÁRSELO AL USUARIO
        public FileStream ArchivoResultante(ref string extension)
        {
            switch (Extension)
            {
                case "txt":
                    var path = RutaAbsolutaServer + NombreArchivo + ".cif";
                    var file = new FileStream(path,FileMode.Open,FileAccess.Read);
                    extension = ".cif";
                    return file;

                case "cif":
                    var path2 = RutaAbsolutaServer + NombreArchivo + ".txt";
                    var file2 = new FileStream(path2, FileMode.Open, FileAccess.Read);
                    extension = ".txt";
                    return file2;
            }
            return null;
        }


        //Reset, para cuando se le da home y que vuelva instanciar
        public void Reset()
        {
            switch (Extension)
            {
                case "cif":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".txt");
                    DescifradoZigZag = new ZigZagDescifrado("","","",0);
                    break;

                case "txt":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".cif");
                    CifradoZigZag = new ZigZagCifrado("", "", "", 0);
                    break;
            }
            Data.Instancia.ArchivoCargado = false;
            Data.Instancia.EleccionOperacion = false;
        }
    }
}

Lab2_Cifrado/Controllers/Serie1/ZigZagController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Controllers.Serie1
{
    public class ZigZagController : Controller
    {
        // GET: ZigZag
        public ActionResult IndexZigZag()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CargaArchivoZigZag(HttpPostedFileBase postedFile)
        {
            var FilePath = string.Empty;

            if (postedFile != null)
            {
                var path = Data.Instancia.RutaAbsolutaServer;

                FilePath = path + Path.GetFileName(postedFile.FileName);
                postedFile.SaveAs(FilePath);

                var nombre = postedFile.FileName.Split('.')[0];

                Data.Instancia.ZigZagCif.AsignarRutas(path,FilePath,nombre);
                Data.Instancia.ZigZagCif.AsignarExtension(postedFile.FileName.Split('.')[1]);

                Data.Instancia.ArchivoCargado = true;
            }

            return RedirectToAction("IndexZigZag");
        }
        
        // POST: ZigZag/Create
        [HttpPost]
        public ActionResult OperarZigZag(FormCollection collection)
        {
            try
            {
                var clave = int.Parse(collection["Clave"]);

                if (clave > 0)
                {
                    Data.Instancia.ZigZagCif.Clave = clave;
                    Data.Instancia.EleccionOperacion = true;
                    Data.Instancia.ZigZagCif.Operar();
                }
                
                return RedirectToAction("IndexZigZag");
            }
            catch (Exception e)
            {
                return View("IndexZigZag");
            }
        }

        //NUEVO PARA DESCARGAR ARCHIVO
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Resultado(FormCollection collection)
        {
            try
            {
                if (collection["DescargarZZ"] != null)
                {
                    return RedirectToAction("DescargarResultadoZigZag");
                }

                if (collection["HomeSerie1"] != null)
                {
                    Data.Instancia.ZigZagCif.Reset();
                    return RedirectToAction("PaginaPrincipalLab", "Home");
                }
            }
            catch(Exception error)
            {
                Data.Instancia.ZigZagCif.Reset();
                return View("IndexZigZag");
            }

            return null;
        }
        
        public FileResult DescargarResultadoZigZag()
        {
            var extensionNueva = string.Empty;

            return File(Data.Instancia.ZigZagCif.ArchivoResultante(ref extensionNueva), "*" + extensionNueva,Data.Instancia.ZigZagCif.NombreArchivo + extensionNueva);
        }
    }
}

Lab2_Cifrado/Views/ZigZag/IndexZigZag.cshtml
@using Lab2_Cifrado.Instancia
@model Lab2_Cifrado.Models.Serie1.ZigZag

@{
    ViewBag.Title = "Zig-Zag |";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h2>Zig-Zag</h2>

@if (Data.Instancia.ArchivoCargado == false)
{
    @Html.Partial("_CargaArchivoZigZag")
}

@if (Data.Instancia.ArchivoCargado && Data.Instancia.EleccionOperacion == false)
{
    @Html.Partial("_OperarZigZag")
}

@if (Data.Instancia.ArchivoCargado && Data.Instancia.EleccionOperacion)
{
    @Html.Partial("_ResultadoZZ")
}

Lab2_Cifrado/Views/ZigZag/_CargaArchivoZigZag.cshtml
@model Lab2_Cifrado.Models.Serie1.ZigZag

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">3. Carga de archivo</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("CargaArchivoZigZag", "ZigZag", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" class="form-control-file" name="postedFile" aria-describedby="fileHelp">
            <br />
            <button type="submit" class="btn btn-info">Cargar</button>
        }
    </div>
</div>

Lab2_Cifrado/Views/ZigZag/_OperarZigZag.cshtml
@model Lab2_Cifrado.Models.Serie1.ZigZag


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">4. Ingrese clave</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("OperarZigZag", "ZigZag"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Cifrar/Descifrar" class="btn btn-info" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Lab2_Cifrado/Views/ZigZag/_ResultadoZZ.cshtml
@using Lab2_Cifrado.Instancia
@model Lab2_Cifrado.Models.Serie1.ZigZag

@using (Html.BeginForm("Resultado","ZigZag"))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">4. Resultado de la operacion</h3>
        </div>
        <div class="panel-body">
            <input type="submit" value="Descargar" class="btn btn-info" name="DescargarZZ" />
            <input type="submit" value="Home" class="btn btn-default" name="HomeSerie1" />
        </div>
    </div>
}