Lab2_Cifrado/Models/Serie3/RSA.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;
using BibliotecaDeClases.Cifrado.RSA;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Models.Serie3
{
    public class RSA
    {
        //P y Q mayores que 0, 1 y 2... son los valores más faciles de descartar en vista, las otras validaciones se harán directo en el controlador
        [Display(Name = "Número P")]
        [Range(17, Int32.MaxValue, ErrorMessage = "P debe ser mayor o igual a 17")]
        [Required(ErrorMessage = "Debe ingresar un valor P")]
        public int P { get; set; }

        [Display(Name = "Número Q")]
        [Range(17, Int32.MaxValue, ErrorMessage = "Q debe ser mayor o igual a 17")]
        [Required(ErrorMessage = "Debe ingresar un valor P")]
        public int Q { get; set; }

        public string NombreArchivo { get; set; }
        private string RutaAbsolutaArchivo { get; set; }
        private string RutaAbsolutaArchivoOperacional { get; set; } //Tendrá la ruta del archivo ya sea private.key o public.key
        private string RutaAbsolutaServer { get; set; }
        private string Extension { get; set; }

        public GenerarLlaves GeneradorLlaves { get; set; }
        public Operaciones OperadorRSA { get; set; }

        public RSA()
        {
            P = 0;
            Q = 0;

            GeneradorLlaves = new GenerarLlaves();

            NombreArchivo = string.Empty;
            RutaAbsolutaArchivo = string.Empty;
            RutaAbsolutaArchivoOperacional = string.Empty;
            RutaAbsolutaServer = string.Empty;
        }

        public void AsignarExtension(string ext)
        {
            Extension = ext;
        }

        public void AsignarRutas(string rutaAbsServer, string rutaAbsArchivo, string nombreArchivo)
        {
            NombreArchivo = nombreArchivo;
            RutaAbsolutaArchivo = rutaAbsArchivo;
            RutaAbsolutaServer = rutaAbsServer;
        }

        public void Operar()
        {
            try
            {
                Operaciones OperardorRSA = new Operaciones(NombreArchivo, RutaAbsolutaArchivo, RutaAbsolutaServer, RutaAbsolutaArchivoOperacional);
                OperardorRSA.OperarRSA(Extension);
                Data.Instancia.SeOperoRSA = true;
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        public FileStream ArchivoResultante(ref string extension)
        {
            switch (Extension)
            {
                case "txt": //Devuelve uno cifrado
                    var pathtxt = RutaAbsolutaServer + NombreArchivo + ".rsacif";
                    var filescif = new FileStream(pathtxt, FileMode.Open, FileAccess.Read);
                    extension = ".rsacif";
                    return filescif;

                case "rsacif": //Devulve uno descifrado
                    var pathscif = RutaAbsolutaServer + NombreArchivo + ".txt";
                    var filetxt = new FileStream(pathscif, FileMode.Open, FileAccess.Read);
                    extension = ".txt";
                    return filetxt;
            }

            return null;
        }

        public FileStream ArchivoResultanteLlave(string tipoLlave)
        {
            RutaAbsolutaServer = Data.Instancia.RutaAbsolutaServer;

            switch (tipoLlave)
            {
                case "public":
                    var path = RutaAbsolutaServer + "public.key";
                    var file = new FileStream(path,FileMode.Open,FileAccess.Read);
                    return file;

                case "private":
                    var path2 = RutaAbsolutaServer + "private.key";
                    var file2 = new FileStream(path2, FileMode.Open, FileAccess.Read);
                    return file2;
            }

            return null;
        }

        public void Reset()
        {
            switch (Extension)
            {
                case "rsacif":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".txt");
                    break;

                case "txt":
                    File.Delete(RutaAbsolutaServer + NombreArchivo + ".rsacif");
                    break;
            }

            Data.Instancia.ArchivoCargado = false;
            Data.Instancia.EleccionOperacion = false;
            Data.Instancia.GenerarLlaves = false;
            Data.Instancia.DescargarLlaves = false;
            Data.Instancia.ExisteError = false;
            Data.Instancia.SeCargoArchivoLlave = false;
            Data.Instancia.SeOperoRSA = false;
        }

        public void AsignarRutaLlaves(string rutaArchivoOperacional)
        {
            RutaAbsolutaArchivoOperacional = rutaArchivoOperacional;
        }

    }
}

Lab2_Cifrado/Controllers/Serie3/RSAController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Controllers.Serie3
{
	public class RSAController : Controller
	{
		// GET: RSA
		public ActionResult IndexRSA()
		{
			//Verifica si es necesario borrar los archivos de llaves del servidor
			if (Data.Instancia.DescargarLlaves == false && System.IO.File.Exists(Data.Instancia.RutaAbsolutaServer + "private.key") && System.IO.File.Exists(Data.Instancia.RutaAbsolutaServer + "public.key"))
			{
				System.IO.File.Delete(Data.Instancia.RutaAbsolutaServer + "private.key");
				System.IO.File.Delete(Data.Instancia.RutaAbsolutaServer + "public.key");
				Data.Instancia.ExisteError = false; //Se niega para que la vista no muestre la ventana emergente de errores
			}

			return View();
		}

		[HttpPost]
		public ActionResult GenerarLlavesRSA(FormCollection collection)
		{
			try
			{
				var p = int.Parse(collection["P"]);
				var q = int.Parse(collection["Q"]);

				if (p > 16 && q > 16)
				{
                    Data.Instancia.ExisteError = false;

                    if (!Data.Instancia.RSA_Cif.GeneradorLlaves.EsPrimo(p) ||
						!Data.Instancia.RSA_Cif.GeneradorLlaves.EsPrimo(q))
					{
						Data.Instancia.ExisteError = true;
						Data.Instancia.Error = 1;
					}
					else if (Data.Instancia.RSA_Cif.GeneradorLlaves.MCD(p, q) != 1
					) //Se está validando de P y Q sean coprimos
					{
						Data.Instancia.ExisteError = true;
						Data.Instancia.Error = 2;
					}

					if (Data.Instancia.ExisteError != true)
					{
						var path = Data.Instancia.RutaAbsolutaServer;
						Data.Instancia.RSA_Cif.GeneradorLlaves.AsignarRutaRaiz(path);

						if (Data.Instancia.RSA_Cif.GeneradorLlaves.GenerarClaves(p, q))
						{
							Data.Instancia.GenerarLlaves = false;
							Data.Instancia.DescargarLlaves = true;
							Data.Instancia.ExisteError = false;
							Data.Instancia.SeCargoArchivoLlave = true;
						}
						else
						{
							Data.Instancia.GenerarLlaves = true;
							Data.Instancia.DescargarLlaves = false;
							Data.Instancia.ExisteError = true;
						}

						
					}
				}
				else
				{
					Data.Instancia.ExisteError = true;
					Data.Instancia.Error = 0;
				}

				return RedirectToAction("IndexRSA");
			}
			catch(Exception exception)
			{
                Data.Instancia.ExisteError = true;

                if (exception.Message == "Inverso modular")
                {
                    Data.Instancia.Error = 4;
                }
				return View("IndexRSA");
			}
		}
		
		//PARA DESCARGAR ALGUN ARCHIVO, YA SEA DE LLAVES O RESULTANTE
		[AcceptVerbs(HttpVerbs.Post)]
		public ActionResult ResultadoRSA(FormCollection collection)
		{
			try
			{
				if (collection["DescargarRSA"] != null)
				{
					return RedirectToAction("DescargarResultadoRSA");
				}

				if (collection["DescargarPublica"] != null)
				{
					return RedirectToAction("DescargaLlavePublica");
				}

				if (collection["DescargarPrivada"] != null)
				{
					return RedirectToAction("DescargaLlavePrivada");
				}

				if (collection["HomeSerie3"] != null)
				{
					Data.Instancia.RSA_Cif.Reset();
					return RedirectToAction("PaginaPrincipalLab", "Home");
				}

				if (collection["ContinuarRSA"] != null)
				{
					System.IO.File.Delete(Data.Instancia.RutaAbsolutaServer + "private.key");
					System.IO.File.Delete(Data.Instancia.RutaAbsolutaServer + "public.key");
					Data.Instancia.ExisteError = false;
					return RedirectToAction("IndexRSA");
				}

			}
			catch
			{
				Data.Instancia.RSA_Cif.Reset();
				return View("IndexRSA");
			}
			return null;
		}

		public FileResult DescargarResultadoRSA()
		{
			var extensionNueva = string.Empty;

			return File(Data.Instancia.RSA_Cif.ArchivoResultante(ref extensionNueva), "*" + extensionNueva, Data.Instancia.RSA_Cif.NombreArchivo + extensionNueva);
		}

		public FileResult DescargaLlavePublica()
		{
			Data.Instancia.DescargarLlaves = false;
			return File(Data.Instancia.RSA_Cif.ArchivoResultanteLlave("public"), "*.key", "public.key");
		}

		public FileResult DescargaLlavePrivada()
		{
			Data.Instancia.DescargarLlaves = false;
			return File(Data.Instancia.RSA_Cif.ArchivoResultanteLlave("private"), "*.key", "private.key");
		}

		[HttpPost]
		public ActionResult CargarArchivoLlave(HttpPostedFileBase postedFile)
		{
			var filePath = string.Empty;

			if (postedFile != null)
			{
				var path = Data.Instancia.RutaAbsolutaServer;
				filePath = path + Path.GetFileName(postedFile.FileName);
				postedFile.SaveAs(filePath);
				Data.Instancia.RSA_Cif.AsignarRutaLlaves(filePath);
				Data.Instancia.SeCargoArchivoLlave = true;
			}
			return RedirectToAction("OperarRSA");
		}

		[HttpPost]
		public ActionResult CargarAchivoRSA(HttpPostedFileBase postedFile)
		{
			var FilePath = string.Empty;

			if (postedFile != null)
			{
				var path = Data.Instancia.RutaAbsolutaServer;

				FilePath = path + Path.GetFileName(postedFile.FileName);
				postedFile.SaveAs(FilePath);

				var nombre = postedFile.FileName.Split('.')[0];

				Data.Instancia.RSA_Cif.AsignarRutas(path,FilePath, nombre);
				Data.Instancia.RSA_Cif.AsignarExtension(postedFile.FileName.Split('.')[1]);

				Data.Instancia.ArchivoCargado = true;
				Data.Instancia.SeCargoArchivoLlave = false;
			}

			return RedirectToAction("IndexRSA");
		}

		public ActionResult OperarRSA()
		{
			try
			{
				Data.Instancia.RSA_Cif.Operar();
				Data.Instancia.SeOperoRSA = true;

				return RedirectToAction("IndexRSA");
			}
			catch(Exception e)
			{
				return RedirectToAction("IndexRSA");
			}
		}
	}
}

Lab2_Cifrado/Views/RSA/IndexRSA.cshtml
@using Lab2_Cifrado.Instancia
@model Lab2_Cifrado.Models.Serie3.RSA

@{
    ViewBag.Title = "RSA |";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h2>RSA</h2>

@if (Data.Instancia.ExisteError)
{
    @Html.Partial("_Errores")
}

@if (Data.Instancia.GenerarLlaves)
{
    @Html.Partial("_GenerarLlaves")
}

@if (Data.Instancia.GenerarLlaves == false && Data.Instancia.DescargarLlaves)
{
    @Html.Partial("_DescargaLlaves")
}

@if (Data.Instancia.ArchivoCargado == false && Data.Instancia.SeCargoArchivoLlave && Data.Instancia.SeOperoRSA == false && Data.Instancia.GenerarLlaves == false && !Data.Instancia.DescargarLlaves)
{
    @Html.Partial("_CargarArchivoRSA")
}

@if (Data.Instancia.SeCargoArchivoLlave == false && Data.Instancia.ArchivoCargado)
{
    @Html.Partial("_CargarArchivoLlave")
}

@*@if (Data.Instancia.SeOperoRSA == false)
{
    @Html.Partial("_OperarRSA")
}*@

@if (Data.Instancia.ArchivoCargado && Data.Instancia.SeOperoRSA)
{
    @Html.Partial("_ResultadoRSA")
}

Lab2_Cifrado/Views/RSA/_CargarArchivoLlave.cshtml
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">4. Carga de llave para operar RSA</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("CargarArchivoLlave", "RSA", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" class="form-control-file" name="postedFile" aria-describedby="fileHelp">
            <br />
            <button type="submit" class="btn btn-info">Cargar</button>
        }
    </div>
</div>

Lab2_Cifrado/Views/RSA/_CargarArchivoRSA.cshtml
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">3. Carga de archivo a operar</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("CargarAchivoRSA", "RSA", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" class="form-control-file" name="postedFile" aria-describedby="fileHelp">
            <br />
            <button type="submit" class="btn btn-info">Cargar</button>
        }
    </div>
</div>

Lab2_Cifrado/Views/RSA/_DescargaLlaves.cshtml
@model Lab2_Cifrado.Models.Serie3.RSA

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">2. Descarga de Llaves</h3>
    </div>
    <div class="panel-body">

        @using (Html.BeginForm("ResultadoRSA", "RSA"))
        {
            <button type="submit" class="btn btn-default" name="DescargarPublica" value="DescargarPublica">Descargar llave pública</button>
            <button type="submit" class="btn btn-default" name="DescargarPrivada" value="DescargarPrivada">Descargar llave privada</button>
            <button type="submit" class="btn btn-default" name="ContinuarRSA" value="ContinuarRSA">Continuar</button>
        }
    </div>
</div>

Lab2_Cifrado/Views/RSA/_Errores.cshtml
@using Lab2_Cifrado.Instancia

<div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Error: </strong>  @Data.Instancia.Errores[Data.Instancia.Error];
</div>

Lab2_Cifrado/Views/RSA/_GenerarLlaves.cshtml
@model Lab2_Cifrado.Models.Serie3.RSA


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">3. Ingrese valores</h3>
    </div>
    <div class="panel-body">


        @using (Html.BeginForm("GenerarLlavesRSA", "RSA"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.P, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.P, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.P, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Q, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Q, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Q, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Generar" class="btn btn-default" />
                        <small>Recuerde P y Q deben ser números primos, por favor seleccione números mayores a 13</small>
                    </div>
                    
                </div>
            </div>
        }


    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab2_Cifrado/Views/RSA/_ResultadoRSA.cshtml
@using (Html.BeginForm("ResultadoRSA", "RSA"))
{
    @Html.AntiForgeryToken()

    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">5. Resultado de la operacion</h3>
        </div>
        <div class="panel-body">
            <input type="submit" value="Descargar" class="btn btn-info" name="DescargarRSA" />
            <input type="submit" value="Home" class="btn btn-default" name="HomeSerie3" />
        </div>
    </div>
}