Lab2_Cifrado/Controllers/Serie1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab2_Cifrado.Controllers
{
    public class Serie1Controller : Controller
    {
        public ActionResult SelecccionCifrado()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SeleccionCifrado(FormCollection formCollection)
        {
            if (formCollection["ZigZag"] != null)
            {
                return RedirectToAction("IndexZigZag", "ZigZag");
            }

            if (formCollection["Espiral"] != null)
            {
                return RedirectToAction("IndexEspiral", "Espiral");
            }

            if (formCollection["Cesar"] != null)
            {
                return RedirectToAction("IndexCesar", "Cesar");
            }
            return null;
        }
    }
}

Lab2_Cifrado/Controllers/Serie2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Controllers
{
    public class Serie2Controller : Controller
    {
        // GET: Serie2
        public ActionResult SeleccionarOpcion()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SeleccionarOpcion(FormCollection formCollection)
        {
            if (formCollection["CargarPermutaciones"] != null)
            {
                Data.Instancia.ModificarPermutaciones = true;
                return RedirectToAction("IndexSDES", "SDES"); //mandarlo directamente a cargar archivo
            }

            if (formCollection["Continuar"] != null)
            {
                return RedirectToAction("IndexSDES", "SDES");
            }

            return null;
        }
    }
}

Lab2_Cifrado/Controllers/Serie3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab2_Cifrado.Instancia;

namespace Lab2_Cifrado.Controllers
{
    public class Serie3Controller : Controller
    {
        // GET: Serie3
        public ActionResult SeleccionarOpcionSerie3()
        {
            if (Data.Instancia.Errores.Count == 0)
            {
                Data.Instancia.Errores.Add("P y Q deben de ser mayores a cero y mayores a 16, tampoco pueden ser iguales");
                Data.Instancia.Errores.Add("El valor de P y Q deben ser números primos");
                Data.Instancia.Errores.Add("P y Q no son coprimos entre ellos");
                Data.Instancia.Errores.Add("Ocurrió un error inesperado al generar las llaves");
                Data.Instancia.Errores.Add("P y Q no tienen inverso multiplicativo modular, intente con otro par de números primos");
            }

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SeleccionarOpcionSerie3(FormCollection formCollection)
        {
            if (formCollection["GenerarLlaves"] != null)
            {
                Data.Instancia.GenerarLlaves = true;
                return RedirectToAction("IndexRSA", "RSA"); //mandarlo directamente a cargar archivo
            }

            if (formCollection["Continuar"] != null)
            {
                Data.Instancia.SeCargoArchivoLlave = true;
                return RedirectToAction("IndexRSA", "RSA");
            }

            return null;
        }

    }
}

Lab2_Cifrado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Laboratorio 2 Cifrado</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lab 2 Cifrado", "PaginaPrincipalLab", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Serie 1", "SelecccionCifrado", "Serie1")</li>
                    <li>@Html.ActionLink("Serie 2", "SeleccionarOpcion", "Serie2")</li>
                    <li>@Html.ActionLink("Serie 3", "SeleccionarOpcionSerie3", "Serie3")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        <br />
        @RenderBody()

        <div>
            <footer class="col-md-10">
                <hr />
                <p>&copy; @DateTime.Now.Year Laboratorio 2 - Cifrado (Ricardo Chian | Pablo García) </p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>